CREATE TABLE STUDENT (
    SNO VARCHAR2(3 BYTE) NOT NULL ,
    SNAME VARCHAR2(9 BYTE) NOT NULL ,
    SSEX CHAR(2 BYTE) NOT NULL 
);
INSERT INTO STUDENT VALUES ('001', 'KangKang', 'M ');
INSERT INTO STUDENT VALUES ('002', 'Mike', 'M ');
INSERT INTO STUDENT VALUES ('003', 'Jane', 'F ');